# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ca.fabric-taxrefund.com:
  orderer.fabric-taxrefund.com:
  peer0.customsorg.fabric-taxrefund.com:
  peer0.taxrefundorg2.fabric-taxrefund.com:
  peer0.taxrefundorg1.fabric-taxrefund.com:
  peer0.storeorg1.fabric-taxrefund.com:
  peer0.storeorg2.fabric-taxrefund.com:

networks:
  tax_refund:

services:

  ca.fabric-taxrefund.com:
    container_name: ca.fabric-taxrefund.com
    extends:
      file:   docker-compose-base.yaml
      service: ca.fabric-taxrefund.com
    networks:
      - tax_refund

  orderer.fabric-taxrefund.com:
    container_name: orderer.fabric-taxrefund.com
    extends:
      file:   docker-compose-base.yaml
      service: orderer.fabric-taxrefund.com
    networks:
      - tax_refund

  peer0.customsorg.fabric-taxrefund.com:
    container_name: customsorg.fabric-taxrefund.com
    extends:
      file:  docker-compose-base.yaml
      service: peer0.customsorg.fabric-taxrefund.com
    networks:
      - tax_refund

  peer0.taxrefundorg1.fabric-taxrefund.com:
    container_name: taxrefundorg1.fabric-taxrefund.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.taxrefundorg1.fabric-taxrefund.com
    networks:
      - tax_refund

  peer0.taxrefundorg2.fabric-taxrefund.com:
    container_name: taxrefundorg2.fabric-taxrefund.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.taxrefundorg2.fabric-taxrefund.com
    networks:
      - tax_refund


  peer0.storeorg2.fabric-taxrefund.com:
    container_name: storeorg2.fabric-taxrefund.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.storeorg2.fabric-taxrefund.com
    networks:
      - tax_refund

  peer0.storeorg1.fabric-taxrefund.com:
    container_name: storeorg1.fabric-taxrefund.com
    extends:
      file: docker-compose-base.yaml
      service: peer0.storeorg1.fabric-taxrefund.com
    networks:
      - tax_refund

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:x86_64-1.1.0
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.taxrefundorg1.fabric-taxrefund.com:7051
      - CORE_PEER_LOCALMSPID=TaxRefundOrg1MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/taxrefundorg1.fabric-taxrefund.com/users/Admin@taxrefundorg1.fabric-taxrefund.com/msp
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/taxrefundorg1.fabric-taxrefund.com/peers/peero0.taxrefundorg1.fabric-taxrefund.com/tls/ca.crt
      - CORE_CHAINCODE_KEEPALIVE=10
      - TZ=Asia/Seoul
#      - CORE_PEER_TLS_ENABLED=true

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/:/host/var/run/
      - ./chaincode:/opt/gopath/src/github.com/chaincode
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./bashScript/script.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/script.sh
      - ./bashScript/upgradeChaincode.sh:/opt/gopath/src/github.com/hyperledger/fabric/peer/utils.sh

    networks:
      - tax_refund

    depends_on:
      - orderer.fabric-taxrefund.com
      - peer0.customsorg.fabric-taxrefund.com
      - peer0.taxrefundorg1.fabric-taxrefund.com
      - peer0.taxrefundorg2.fabric-taxrefund.com
      - peer0.storeorg2.fabric-taxrefund.com
      - peer0.storeorg1.fabric-taxrefund.com